#!/bin/bash
# chkconfig:	 345 81 29
# description:	Atheme IRC Services
# processname:	atheme-services

### BEGIN INIT INFO
# Provides:		atheme-services
# Require-Start:	$local_fs $remote_fs $network $ngircd $named
# Require-Stop:		$loacl_fs $remote_fs $network $ngircd $named
# Default-Start:	3 4 5
# Default-Stop:		0 1 2 6
# Description:		Atheme IRC Services provides "NickServ" and more for ngIRCd
### END INIT INFO

# Source funcition library.
. /etc/rc.d/init.d/functions

RETVAL=0
prog="Atheme IRC Services"
exec=/usr/bin/atheme-services
pidfile=/var/run/atheme/atheme.pid
lockfile=/var/lock/subsys/atheme


start() {
	echo -n $"Starting $prog: "
	daemon --pidfile $pidfile $exec $OPTIONS
	RETVAL=$?
	[ $RETVAL -eq 0 ] && touch $lockfile
	echo
}

stop(){
	echo -n $"Stopping $prog: "
	killproc -p $pidfile $exec
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f $lockfile
	echo
}

reload() {
	echo -n $"Reloading $prog: "
	killproc -p $pidfile $exec -HUP
	RETVAL=$?
	echo
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  reload)
	reload
	;;
  force-reload|restart)
	stop
	sleep 1
	start
	RETVAL=$?
	;;
  condrestart|try-restart)
	if [ -f $lockfile ]; then
		stop
		sleep 3
		start
	fi
	;;
  status)
	status -p $pidfile $exec
	RETVAL=$?
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|condrestart|reload|status}"
	RETVAL=2
	[ "$1" = "usage" ] && RETVAL=0
esac

exit $RETVAL

